### PR TITLE
Working on a fix for latest stable release of Blender 2.8

### PR DESCRIPTION
**Pull request by vini-guerrero**
I've came across this update for the add-on to fix issues with latest API documentation of Blender:
https://docs.blender.org/api/current/bpy.types.Object.html

This PR fixes the common issue reported in Godot Engine original collada repo:
image
https://github.com/godotengine/collada-exporter/issues/107

However it's still not working properly, it doesn't crash on the export anymore, but I think it's not properly selecting the meshes to export or I might be missing a step. 
Would you mind taking a look at this PR @artellblender ?

Thanks in advance, best regards!

### CODE REVIEW

**Comment by HungryProton** [comment]
@vini-guerrero 
What do you mean by "not selecting the meshes to export"? Does it export everything or nothing at all, regardless of the "Export selected" button or is it something completely different?
 
I tried to fix it too and it seem to work on my computer
Can you try with this version ? https://github.com/HungryProton/collada-exporter-2.8

**Comment by vini-guerrero** [comment]
@HungryProton it threw no errors on export anymore (updated API params), generated the file and animation nodes in Godot, but the mesh itself was empty (invisible), I'll try that branch, thanks!

**Comment by gevonstria** [comment]
Anyone has any suggestions to solve this?

I am also having this error. :(

**Comment by artellblender** [comment]
Thanks for your contribution, i've done other minor modifications to ensure it works with the new API, please see the latest update.
Export from Blender/ import in Godot seems to work, except shape keys animation did not play in Godot.

**Comment by jitspoe** [comment]
Hey, I just gave this a go, and it seems the option to apply modifiers no longer works.  I exported a mesh with a mirror modifier and only got half the mesh.  Looking at the source, it seems "apply_modifiers" is set, but never used.

**Pull request closed without merging**
